-- Migration: 072_fix_competitions_market_constraint.sql
-- 
-- Problem: The check constraint "competitions_active_upcoming_require_market"
-- blocks auto-generated competitions from being created because the ETL 
-- pipeline creates competitions without a linked market_id.
--
-- The competition system evolved: competitions can now be auto-generated 
-- from ETL data clusters without needing a pre-existing market record.
-- The market is optional for system-generated competitions.
--
-- Fix: Replace the strict constraint with a softer one that allows 
-- NULL market_id for auto-generated (metadata->>'autoGenerated' = 'true') 
-- competitions while still enforcing market_id for manually created ones.

-- Step 1: Drop the old strict constraint
ALTER TABLE competitions 
DROP CONSTRAINT IF EXISTS competitions_active_upcoming_require_market;

-- Step 2: Add a relaxed constraint that allows auto-generated competitions 
-- to have NULL market_id while still protecting manual ones
-- Auto-generated competitions (created by ETL) don't need a market_id.
-- Manually created competitions (e.g. from admin dashboard) still require one.
ALTER TABLE competitions 
ADD CONSTRAINT competitions_require_market_unless_autogenerated
CHECK (
    -- Allow any status that is NOT active/upcoming
    status NOT IN ('active', 'upcoming')
    -- OR allow if market_id is present
    OR market_id IS NOT NULL
    -- OR allow if it's auto-generated by the system
    OR (metadata->>'autoGenerated')::boolean = true
    -- OR allow if it's a sports competition with an event reference
    OR (metadata->>'source') IS NOT NULL
);

-- Step 3: Verify the constraint works by checking existing records
-- This is a no-op query, just for validation
DO $$
BEGIN
    RAISE NOTICE '✅ Constraint competitions_require_market_unless_autogenerated applied successfully';
END $$;
