import { Module, MiddlewareConsumer, NestModule } from '@nestjs/common';
import { ConfigModule } from '@nestjs/config';
import { ScheduleModule } from '@nestjs/schedule';
import { AuthModule } from './modules/auth/auth.module.js';
import { UsersModule } from './modules/users/users.module.js';
import { DashboardModule } from './modules/dashboard/dashboard.module.js';
import { MarketsModule } from './modules/markets/markets.module.js';
import { OrdersModule } from './modules/orders/orders.module.js';
import { DepositModule } from './modules/deposits/deposit.module.js';
import { AdminModule } from './modules/admin/admin.module.js';
import { SecurityModule } from './modules/security/security.module.js';
import { NotificationsModule } from './modules/notifications/notifications.module.js';
import { SettingsModule } from './modules/settings/settings.module.js';
import { ReferralsModule } from './modules/referrals/referrals.module.js';
import { TransactionsModule } from './modules/transactions/transactions.module.js';
import { SportsModule } from './modules/sports/sports.module.js';
import { EmailModule } from './modules/email/email.module.js';
import { AgentsModule } from './modules/agents/agents.module.js';
import { CompetitionsModule } from './modules/competitions/competitions.module.js';
import { PoolModule } from './modules/pool/pool.module.js';
import { DatabaseModule } from './database/database.module.js';
import { HealthController } from './health.controller.js';
import { RootController } from './root.controller.js';
import { envSchema } from './config/env.validation.js';
import { LoggerMiddleware } from './common/middleware/index.js';
import { AuditLogInterceptor } from './common/interceptors/index.js';

/**
 * Root Application Module
 *
 * Architecture notes (NestJS + Fastify):
 * - Security headers, input sanitization, and rate limiting are
 *   registered as Fastify plugins/hooks in main.ts for maximum performance
 * - NestJS middleware is used only for request logging (adapter-agnostic)
 * - Guards, interceptors, and pipes remain NestJS-level (adapter-agnostic)
 * - This separation ensures Fastify's performance is not degraded by
 *   Express compatibility layer overhead
 */
@Module({
    imports: [
        // Configuration with validation
        ConfigModule.forRoot({
            isGlobal: true,
            envFilePath: ['.env.local', '.env'],
            validate: (config) => envSchema.parse(config),
            cache: true,
        }),

        // Database
        DatabaseModule,

        // Security (Global)
        SecurityModule,

        // Core Feature Modules
        AuthModule,
        UsersModule,
        DashboardModule,
        MarketsModule,
        OrdersModule,
        DepositModule,

        // New Modules
        AdminModule,
        NotificationsModule,
        SettingsModule,
        ReferralsModule,
        TransactionsModule,
        SportsModule,
        EmailModule,
        AgentsModule,
        CompetitionsModule,
        PoolModule,

        // Scheduling
        ScheduleModule.forRoot(),
    ],
    controllers: [RootController, HealthController],
    providers: [
        AuditLogInterceptor,
    ],
    exports: [
        AuditLogInterceptor,
    ],
})
export class AppModule implements NestModule {
    configure(consumer: MiddlewareConsumer) {
        // Only apply logger middleware (lightweight, adapter-agnostic)
        // Security headers + input sanitization are Fastify hooks (main.ts)
        // Request IDs are generated by Fastify's genReqId (main.ts)
        consumer
            .apply(LoggerMiddleware)
            .forRoutes('*');
    }
}
