import { Injectable, Logger } from '@nestjs/common';
import { SupabaseService } from '../../../database/supabase.service.js';

const CATEGORY_QUOTAS: Record<string, number> = {
    politics: 5,
    finance: 5,
    crypto: 5,
    tech: 5,
    economy: 5,
    science: 5,
    sports: 5,
};

@Injectable()
export class CompetitionManagerService {
    private readonly logger = new Logger(CompetitionManagerService.name);

    constructor(private readonly supabaseService: SupabaseService) {}

    /**
     * Checks if a category needs more active competitions.
     * Returns the number of slots available.
     */
    async getAvailableSlots(category: string): Promise<number> {
        const quota = CATEGORY_QUOTAS[category.toLowerCase()] || 0;
        if (quota === 0) return 0;

        const supabase = this.supabaseService.getAdminClient();

        const { count, error } = await supabase
            .from('competitions')
            .select('*', { count: 'exact', head: true })
            .eq('sector', category.toLowerCase())
            .in('status', ['active', 'upcoming']);

        if (error) {
            this.logger.error(`Error checking slots for ${category}: ${error.message}`);
            return 0;
        }

        const activeCount = count || 0;
        return Math.max(0, quota - activeCount);
    }

    /**
     * Creates a new AI Competition for a given category.
     */
    async createCompetition(category: string, title: string, description: string, timeHorizon: string, baseProbability: number = 0.5): Promise<any> {
        const supabase = this.supabaseService.getAdminClient();

        // Map time horizon to duration
        const durationMap: Record<string, number> = {
            '2h': 2 * 60 * 60 * 1000,
            '7h': 7 * 60 * 60 * 1000,
            '12h': 12 * 60 * 60 * 1000,
            '24h': 24 * 60 * 60 * 1000,
            '3d': 3 * 24 * 60 * 60 * 1000,
            '7d': 7 * 24 * 60 * 60 * 1000,
        };

        const duration = durationMap[timeHorizon] || durationMap['24h'];
        const start = Date.now();
        const end = start + duration;

        const { data, error } = await supabase.from('competitions').insert({
            title,
            description,
            sector: category.toLowerCase(),
            status: 'active',
            competition_start: new Date(start).toISOString(),
            competition_end: new Date(end).toISOString(),
            time_horizon: timeHorizon,
            base_probability: baseProbability,
            probabilities: [Math.round(baseProbability * 10000), 10000 - Math.round(baseProbability * 10000)],
            metadata: { autoGenerated: true, source: 'etl-pipeline' }
        }).select('*').single();

        if (error) {
            this.logger.error(`Failed to create competition: ${error.message}`);
            return null;
        }

        this.logger.log(`Created new competition: ${title} (${timeHorizon}) in ${category}`);
        return data;
    }
}
