-- Migration: Add metadata column to markets table for ETL-generated markets
-- This column stores additional data like source, external event IDs, and auto-generation info

-- Add metadata JSONB column to markets table
ALTER TABLE markets ADD COLUMN IF NOT EXISTS metadata JSONB DEFAULT '{}';

-- Add index for querying metadata fields
CREATE INDEX IF NOT EXISTS idx_markets_metadata ON markets USING gin(metadata);

-- Add index for auto-generated markets filtering
CREATE INDEX IF NOT EXISTS idx_markets_auto_generated ON markets ((metadata->>'autoGenerated'));

-- Add comment
COMMENT ON COLUMN markets.metadata IS 'Additional metadata for ETL-generated and auto-created markets';
